---
title: "Project"
author: "Emily Medema"
date: '2019-03-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project: Pokemon Dataset

```{r}
pokemon<-read.csv("pokemon_alopez247.csv")
#plot(pokemon)
plot(pokemon$Name~pokemon$Type_1)
plot(pokemon$Name~. , data = pokemon, col = "blueviolet")
#look at all those tasty graphs

```

Let's try fitting a linear model with the response variable total and predictors HP, Attack, and Defense.

```{r}
linmod <- lm(pokemon$Total~pokemon$HP+pokemon$Attack+pokemon$Defense)
summary(linmod)
#plot(linmod)
plot(pokemon$HP+pokemon$Attack+pokemon$Defense, pokemon$Total)
abline(linmod, h = 0.5, col = "red")
#mmmm tasty sig values
```


First attempt at Clustering
```{r}
eucdist<-dist(pokemon, method="euclidean")
clusPokemon<-hclust(eucdist, method = "single")
plot(clusPokemon)
clusPokemonAvg<-hclust(eucdist, method = "average")
plot(clusPokemonAvg)
clusComplete<-hclust(eucdist, method = "complete")
plot(clusComplete)
```


