---
title: "R Notebook"
output: html_notebook
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
```

#laurenedits

```{r}
data = read.csv("pokemon_alopez247.csv", header=T)
```

```{r}
summary(data)
```

```{r}
library(scatterplot3d) 
attach(pokemon) 
scatterplot3d(HP,Defense,Pr_Male, pch=16, highlight.3d=TRUE,
  type="h", main="3D Scatterplot")
```

```{r}
library(scatterplot3d)
attach(pokemon)
scatterplot3d(Defense,HP,Pr_Male, main="3D Scatterplot")
```

```{r}
library(gclus)
dta <- pokemon[c(5,6,7,8)] # data, numbers as column numbers 
dta.r <- abs(cor(dta)) # correlation
dta.col <- dmat.color(dta.r) # colors
dta.o <- order.single(dta.r) 
cpairs(dta, dta.o, panel.colors=dta.col, gap=.5,
main="Variables Ordered and Colored by Correlation" )
```

```{r}
set.seed(763)
library(tree)
trainindex <- sample(1:nrow(pokemon), 721)
proftrain <- salaries[trainindex, ]
proftest <- salaries[-trainindex, ]
predictTotal <- tree(Total~., data=proftrain)
plot(predictTotal)
text(predictTotal, pretty=0)
predict(predictTotal, proftest)
mean((predict(predictTotal, proftest) - proftest$Total)^2)
summary(predictTotal)
```

Neural net testing isLegendary w/ all
```{r}
library(nnet)
library(NeuralNetTools)
set.seed(53747958)
numeric_col <- c(5:12, 16, 20:21)
pokemon[,numeric_col] <- scale(pokemon[,numeric_col])
colnames(data)[22]<-"isLegendary"
nnpokemon<-nnet(isLegendary~., data = data, size = 1)
plotnet(nnpokemon)
mean(nnpokemon$residuals^2)
```

Neural net testing isLgendary w/ Defense+Pr_Male+Attack+HP
```{r}
library(nnet)
library(NeuralNetTools)
set.seed(53747958)
numeric_col <- c(5:12, 16, 20:21)
pokemon[,numeric_col] <- scale(pokemon[,numeric_col])
trainset <- pokemon[1:505, ]
testset <- pokemon[506:721, ]
colnames(data)[22]<-"Pr_Male"
nnpokemon<-neuralnet(isLegendary~Defense+Pr_Male+Attack+HP,data=pokemon, hidden=3,act.fct = "logistic",
                linear.output = FALSE)
plotnet(nnpokemon)
```


```{r}
test=data.frame(Defense,Pr_Male,Attack,HP)
Predict=compute(nnpokemon,test)
Predict$net.result
```

```{r}
prob <- Predict$net.result
pred <- ifelse(prob>0.5, 1, 0)
pred
```

```{r}
#Test the resulting output
temp_test <- subset(testset, select = c("Defense","Pr_Male", "Attack", "HP"))
head(temp_test)
nn.results <- compute(nnpokemon, temp_test)
results <- data.frame(actual = testset$isLegendary, prediction = nn.results$net.result)
```


```{r}
pokemon <- read.csv("~/pokemon_alopez247.csv", stringsAsFactors = FALSE)
#remove NA from dataset
cleanPoke <- na.omit(pokemon)
pcPoke <- prcomp(as.matrix(cleanPoke[,c(5:8,16)]), scale. = TRUE)
summary(pcPoke)
```

```{r}
biplot(pcPoke)
```

```{r}
plot(pcPoke$x[,1:2])
```

```{r}
plot(pcPoke$x[,1:2], type="n")
text(pcPoke$x[,1], pcPoke$x[,2], labels = 1:nrow(pokemon))
```

```{r}
round(pcPoke$rotation[,1:2], 2)
```

```{r}
pokemon[order(pcPoke$x[,1], decreasing=TRUE)[1:4], 1:3]
```

```{r}
test1 <- hclust(dist(scale(pokemon[,-c(2, 3, 4, 12, 13, 14, 15, 16, 17, 18, 19, 23)])))
plot(test1)
test2 <- hclust(dist(pcPoke$x))
plot(test2)
```

```{r}
all.equal(dist(scale(pokemon[,-c(2, 3, 4, 12, 13, 14, 15, 16, 17, 18, 19, 23)])), dist(pcPoke$x), check.attributes = FALSE)
```