---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#laurenedits

```{r}
data = read.csv("pokemon_alopez247.csv", header=T)
```

```{r}
library(nnet)
library(NeuralNetTools)
library(neuralnet)
set.seed(53747958)
numeric_col <- c(5:12, 16, 20:21)
pokemon[,numeric_col] <- scale(pokemon[,numeric_col])
set.seed(1995)
train<-sample(1:nrow(pokemon),505)
testset<-poke[-train,]
trainset<-poke[train,]
```

```{r}
set.seed(2019)
# colnames(data)[22]<-"isLegendary"
nn <- neuralnet(isLegendary ~ Attack + Defense + HP + Sp_Atk + Sp_Def + Speed,data=trainset, hidden=c(6,3), linear.output=TRUE, threshold=0.01)
nn$result.matrix
plotnet(nn)
?neuralnet
```

```{r}
#table(btest[,25], predict(nnbodtr, newdata=btest[,-25], type="class"))
nn.results<-predict(nn,newdata=testset,type="class")
# nn.results
results <- data.frame(actual = testset$isLegendary, prediction = nn.results)
results
```

```{r}
for(i in 1:nrow(results)) {
  results[i,4]<-as.integer(results[i,2])
}
results[,4]<-as.logical(results[,4])
results
```

```{r}
table(results$actual,results[,4])
```

```{r}
# predicted=results$prediction * abs(diff(range(isLegendary))) + min(isLegendary)
# actual=results$actual * abs(diff(range(isLegendary))) + min(isLegendary)
# comparison=data.frame(predicted,actual)
# deviation=((actual-predicted)/actual)
# comparison=data.frame(predicted,actual,deviation)
# accuracy=1-abs(mean(deviation))
# accuracy
```

Ok, let's try using nnet since neuralnet doesn't do categorical response:

```{r}
library(gclus)
library(nnet)
library(NeuralNetTools)
set.seed(1995)
spoke <- cbind(scale(trainset[,6:11]), factor(trainset$isLegendary))
colnames(spoke)[7] <- "isLegendary"
spoke<-data.frame(spoke)
nnpoke <- nnet(factor(isLegendary)~., data=spoke, size=4)
table(trainset$isLegendary, predict(nnpoke, type="class"))


plotnet(nnpoke)
```

```{r}
spoke
```


```{r}
spoketest <- cbind(scale(testset[,6:11]), factor(testset$isLegendary))
colnames(spoketest)[7] <- "isLegendary"
spoketest<-data.frame(spoketest)
table(spoketest$isLegendary, predict(nnpoke, newdata=spoketest, type="class"))
```

That's pretty damn good for misclass!


##Regression neural net for catch rate

```{r}
set.seed(1995)
train<-sample(1:nrow(pokemon),505)
testset<-poke[-train,]
trainset<-poke[train,]
```

```{r}
# trainset[,22]<-scale(trainset[,22])
head(trainset)
# trainset
```

```{r}
set.seed(220734532)
nncatch <- neuralnet(Catch_Rate ~ Attack + Defense + HP + Sp_Atk + Sp_Def + Speed,data=trainset, hidden=c(5,4,3,2), threshold=0.01)
nn$result.matrix
plotnet(nncatch)
```

Calculate some errors!!

```{r}
sum((predict(nncatch, data.frame(testset))-testset$Catch_Rate)^2)#/length(trainset)
mse<-sum((compute(nncatch, testset[,6:11])$net.result-testset$Catch_Rate)^2)
mse
```



```{r}
linmod<-lm(Catch_Rate~Attack+Defense+HP+Sp_Atk+Sp_Def+Speed,data=trainset)
sum((predict(linmod,data.frame(testset))-testset$Catch_Rate)^2)

```


```{r}
trainsetg<-trainset[which(hasGender=='True'),]
testsetg<-testset[which(hasGender=='True'),]
trainsetg<-na.omit(trainsetg)
trainsetg
testsetg<-na.omit(testsetg)
testsetg
```

```{r}
set.seed(9065342)
nnmale <- neuralnet(Pr_Male ~ Attack + Defense + HP + Sp_Atk + Sp_Def + Speed,data=trainsetg, hidden=c(4,3), threshold=0.01)
plotnet(nnmale)
```

```{r}
mse<-sum((compute(nnmale, testsetg[,6:11])$net.result-testsetg$Pr_Male)^2)
mse
```

```{r}
for(i in 1:5){
  nnmaletr <- neuralnet(Pr_Male ~ Attack + Defense + HP + Sp_Atk + Sp_Def + Speed,data=trainsetg, hidden=c(3,i), threshold=0.01)
  print(paste("Number of hidden layer variables in second layer:", i))
  print(paste("MSE: ",sum((compute(nnmaletr, testsetg[,6:11])$net.result-testsetg$Pr_Male)^2)))
}
```

```{r}
set.seed(906534)
nnmale <- neuralnet(Pr_Male ~ Attack + Defense + HP + Sp_Atk + Sp_Def + Speed,data=trainsetg, hidden=c(3,1), threshold=0.01)
plotnet(nnmale)
mse<-sum((compute(nnmale, testsetg[,6:11])$net.result-testsetg$Pr_Male)^2)
mse
```


```{r}
linmod<-lm(Pr_Male ~ Attack + Defense + HP + Sp_Atk + Sp_Def + Speed,data=trainsetg)
sum((predict(linmod,newdata=testsetg)-testsetg$Pr_Male)^2)
```

