---
title: "R Notebook"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#laurenedits

```{r}
data = read.csv("data/pokemon_alopez247.csv", header=T)
```

```{r}
summary(data)
```


#Principle Component Analysis
```{r}
pokemon <- read.csv("data/pokemon_alopez247.csv", stringsAsFactors = FALSE)
#remove NA from dataset
cleanPoke <- na.omit(pokemon)
pcPoke <- prcomp(as.matrix(cleanPoke[,c(5:8,16)]), scale. = TRUE)
summary(pcPoke)
```

```{r}
biplot(pcPoke)
```

```{r}
plot(pcPoke$x[,1:2])
```

```{r}
plot(pcPoke$x[,1:2], type="n")
text(pcPoke$x[,1], pcPoke$x[,2], labels = 1:nrow(pokemon))
```

```{r}
round(pcPoke$rotation[,1:5], 3)
```

```{r}
pokemon[order(pcPoke$x[,1], decreasing=TRUE)[1:4], 1:3]
plot(pcPoke, type="lines")
abline(a=1, b=0, col="blue", lwd=3)
```

```{r}
test1 <- hclust(dist(scale(pokemon[,-c(2, 3, 4, 12, 13, 14, 15, 16, 17, 18, 19, 23)])))
plot(test1)
test2 <- hclust(dist(pcPoke$x))
plot(test2)
```

```{r}
all.equal(dist(scale(pokemon[,-c(2, 3, 4, 12, 13, 14, 15, 16, 17, 18, 19, 23)])), dist(pcPoke$x), check.attributes = FALSE)
```