---
title: "Logistic Regression"
author: "Kat"
date: '2019-03-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pokemon<-read.csv("pokemon_alopez247.csv")

# set.seed(1995)
# train<-sample(1:nrow(poke),432)
# poke.train<-poke[train, ]
# poke.test<-poke[-train, ]

```

Turning all data into numerics

```{r}
poke<-data.frame(pokemon)

#remove unique identifiers
poke<-poke[,-c(1,2)]
```

```{r}
for(j in 1:ncol(poke)){
  if(!is.numeric(poke[,j]) ){
      poke[,j]<-(as.numeric(poke[,j]))
  }
}

poke$isLegendary <- (poke$isLegendary - 1)
poke$hasMegaEvolution <- (poke$hasMegaEvolution - 1)
poke$hasGender <- (poke$hasGender - 1)
```


## Logistic Regression

```{r}
library(class)
library(boot)
library("gclus")

# typeglm <- glm(poke.train$hasGender~poke.train$Type_1 + poke.train$Type_2, data=poke.train)
# typeglm
# predgend<- predict(typeglm, newdata = poke.test, type= "response")
# predgend
# predgend2<- predgend[c(1:289)]
# length(poke.test$hasGender)
# table(predgend2>0.5, poke.test$hasGender)
```
isLegendary ~ hasGender + Catch_Rate

```{r}
pokeglm<- glm(isLegendary ~ hasGender + Catch_Rate, family = "binomial", data = poke)
summary(pokeglm)
```

ok so the t test variable selection says all of the variables are important.
This might be Type 1 error??? (probs nah tbh why would a legendary pokemon need a gender or be easy to catch?)


Leave One Out Cross Validation!
```{r}

attach(poke2)
pokeglm <- list()
cv.mse <- NA
for(i in 1:nrow(poke)){
  cvisLeg <- poke$isLegendary[-i]
  cvhasGend <- poke$hasGender[-i]
  cvCatchR <- poke$Catch_Rate[-i]
  
  pokeglm[[i]]<- glm(cvisLeg ~ cvhasGend + cvCatchR, family = "binomial")
  cv.mse[i] <- (predict(pokeglm[[i]], newdata = data.frame(poke$isLegendary[i])) - poke$isLegendary[i])^2
  
}

mean(cv.mse)

```

